name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: docker hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: spring-backend build
        uses: docker/build-push-action@v5
        with:
          context: ./bend/uek223-gruppe2-backend/spring_backend
          file: Dockerfile
          push: true
          tags: myorg/spring-api:latest

      - name: react-frontend build
        uses: docker/build-push-action@v5
        with:
          context: ./fend/uek223-gruppe2-frontend/react_frontend
          file: Dockerfile
          push: true
          tags: myorg/react-ui:latest